### ISSUE TITLE
Supervised Machine Learning for Text Analysis in R

### ISSUE THREAD

**Issue by readyready15728** [libera-math/libera-math.github.io#3]
https://smltar.com

This book is pretty good.

**Comment by readyready15728** [comment]
For the requested summary: "Supervised Machine Learning for Text Analysis in R provides comprehensive instruction in statistical regression and classification using the modern Tidyverse ecosystem for R, including random forest, SVM and deep learning models."

**Comment by int-e** [comment]
Thanks, I've added the entry!
